name: ipados_menu_bar
description:
  "A Flutter package that brings the iPadOS menubar to your apps, offering a native-like, customizable menu experience for iPad."
version: 0.4.0
repository: https://github.com/ELadrimonos/ipados_menu_bar
issue_tracker: https://github.com/ELadrimonos/ipados_menu_bar/issues

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IpadOSMenubarPlugin
